## Settings
title: Perldot
url: "https://thibaultduponchelle.github.io/perldot"
baseurl: "https://thibaultduponchelle.github.io/perldot"
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
latest: 5.32.0
github: "thibaultduponchelle/perldot"
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mentions
