## Settings
title: Perldot
url: ""
baseurl: ""
permalink: /perldot/blog/:title
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
latest: 5.34.0
github: "thibaultduponchelle/perldot"
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mentions
