## Settings
title: Code Poison
owner: ""
url: "https://thibaultduponchelle.github.io/codepoison"
baseurl: ""
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
github: "thibaultduponchelle/codepoison"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "Black Magic"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: '~!@#$%^&*)(_-=+;:{}[]|\/<>,.'
plugins:
  - jemoji

