## Settings
title: Perldot
url: "/perldot"
baseurl: "/blog"
permalink: "/blog/:title"
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
latest: 5.34.0
github: "thibaultduponchelle/perldot"
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mentions
