name : SVN-cpm-2

on:
  schedule:
    - cron: 0 12 * * *

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install some debs
        run: sudo apt-get install libaprutil1-dev libsqlite3-dev libgettextpo-dev
      - name: Install alien
        run: curl -sL https://git.io/cpm | perl - install --show-build-log-on-failure --test Alien::SVN
