name: alien-river-only-5-problem-childs

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install aliens
        run: curl -sL https://git.io/cpm | perl - install --show-build-log-on-failure --cpanfile=cpanfile-alien-river-only-5-problem-childs
