name : DBD-SQLite-BundlerExtensions

on:
  schedule:
    - cron: 0 12 * * *

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install alien
        run: curl -sL https://git.io/cpm | perl - install --show-build-log-on-failure --test dirt/DBD-SQLite-BundledExtensions-0.002.tar.gz
