name: gearman-macos-build

on: 
  push:
    branches: foobar
  
jobs:
  gearman:
    runs-on: macOS-latest
    steps:
      - name: Deps 
        run: |
          brew install boost
      - name: Download
        run: |
          wget https://github.com/gearman/gearmand/releases/download/1.1.19.1/gearmand-1.1.19.1.tar.gz
          tar xvzf gearmand-1.1.19.1.tar.gz
      - name: Configure
        run: |
          cd gearmand-1.1.19.1
          ./configure
          make
