name: linux-check-syntax
on: 
  schedule:
    - cron: 0 0 * * *

jobs:
  perl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: perl -V
      run: perl -V
    - name: Check syntax 
      run: for f in `find . -name "*.pm" -o -name "*.pl" -o -name "*.t"`; do perl -c $f; done


