name: perl-critic
on: 
  schedule:
    - cron: 0 0 * * *

jobs:
  perl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: perl -V
      run: perl -V
    - name: Perl Critic
      uses: Difegue/action-perlcritic@master
      with:
        args: ./lib/* ./scripts/*


