name : ping-google-ipv6

on: [pull_request]

jobs:
  ping:
    runs-on: ubuntu-18.04
    steps:
      - name: check ipv6
        run: cat /sys/module/ipv6/parameters/disable
      - name: ping ipv6
        run: timeout 10 ping -6 2001:4860:4860::8888
