name: problem-childs

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install libdb
        run: |
          sudo apt-get update
          sudo apt-get install libdb-dev
      - name: Install Dependencies
        run: curl -sL https://git.io/cpm | perl - install --show-build-log-on-failure XML::Parser DB_File Net::SSLeay Math::BigInt::GMP
