name: windows-cpanminus

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  perl:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Perl
        run: |
          choco install strawberryperl
          curl https://cpanmin.us | perl - App::cpanminus -n
          echo "##[add-path]C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: cpanm --cpanfile=cpanfile --installdeps . --verbose
      - name: Run Tests
        run: prove -l t

