name : Alien-SVN-fails-if-Alien-gettext-is-installed

on:
  schedule:
    - cron: 0 12 * * *

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Check installed debs
        run: sudo dpkg -l
      - name: Install some debs
        run: sudo apt-get install libaprutil1-dev libsqlite3-dev
      - name: Install Alien::Base::ModuleBuild needed by Alien::gettext
        run: curl -sL https://git.io/cpm | perl - install --show-build-log-on-failure --test Alien::Base::ModuleBuild
      - name: Install Alien::gettext
        run: curl -sL https://git.io/cpm | perl - install --show-build-log-on-failure --test Alien::gettext
      - name: Install Alien::SVN
        run: curl -sL https://git.io/cpm | perl - install --show-build-log-on-failure --test Alien::SVN
