name: build-docker-image-with-action

on:
  push:
    branches: foobar

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - name: Fetch repository
        uses: actions/checkout@master

      - name: Publish docker
        id: docker
        uses: zenato/docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: youruser/yourrepo
          tag: latest
