name: cpm-broken-on-fedora
on:
  schedule:
    - cron: 0 0 * * *

jobs:
  perl:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        img:
          - 'fedora:26'
          - 'fedora:30'
         
    container:
      image: ${{ matrix.img }}

    steps:
      - name: Eventually install Perl on Fedora and centos
        run: yum install perl -y || true
      - name: perl -V
        run: perl -V
      - name: Install alien
        run: curl -sL https://git.io/cpm | perl - install --show-build-log-on-failure Acme::LSD
