name: gearman-macos-build-extern

on:
  push:
    branches: foobar
  
jobs:
  gearman:
    runs-on: macOS-latest
    steps:
      - name: Deps 
        run: |
          brew install boost
      - name: Download
        run: |
          wget https://github.com/thibaultduponchelle/messy-perl-ci-workflows/raw/master/dirt/gearmand-1.1.19.1-extern.tar.gz
          tar xvzf gearmand-1.1.19.1-extern.tar.gz
      - name: Configure
        run: |
          cd gearmand-1.1.19.1-extern
          ./configure
          make
