name: perl-5.10.1-on-recent-ubuntu

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - name: Install cpanm with vendor Perl
        run: curl -L http://cpanmin.us | perl - --sudo App::cpanminus
      - name: Build Perl 5.10.1
        run: | 
          wget https://www.cpan.org/src/5.0/perl-5.10.1.tar.gz
          tar xvzf perl-5.10.1.tar.gz
          sudo cpanm Devel::PatchPerl
          patchperl perl-5.10.1
          cd perl-5.10.1
          ./Configure -des -Dprefix=/opt/perl5.10.1 -Aldflags='-lm'
          make 
          sudo make install
      - name: perl -V
        run: /opt/perl5.10.1/bin/perl -V
