name: sodium

on: 
  schedule:
    - cron: 0 0 * * *

jobs:
  perl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: perl -V
      run: perl -V
    - name: Install cpanm
      run: curl -L http://cpanmin.us | perl - --sudo App::cpanminus
    - name: Install Dependencies
      run: cpanm dirt/Alien-Sodium-1.0.8.1.tar.gz
    - name: Run Tests
      run: prove -l t
